spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: BlogPlatform

  datasource:
    url: jdbc:mysql://localhost:3305/exampledb
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: a1204f3bb67184bddb76309bd575ddb88ecdb5cdb8a877e902b055b6150776ae
    refresh: a1204f3bb67184bddb76309bd575ddb88ecdb5cdb8a877e902b055b6150776ae